### ISSUE TITLE
PeaZip cannot open or create files with CJK characters in their name

### ISSUE THREAD

**Issue by lmy441900** [giorgiotani/PeaZip#11]
Recently I updated my Windows 10 to 10586, and PeaZip doesn't work when the compressed files' name contain CJK characters (like Chinese). It remind me to enter password (However those files are not encrypted). PeaZip cannot create archives whose name contain CJK characters, neither.

Files with English names are normally read and extracted.

However when I use `cmd` to execute `7z`, it works. That means, the connection between PeaZip's GUI front-end and 7-zip back-end breaks.

I have noticed that in Windows 10 10586 the Command Prompt had been updated to a new version, but I'm not sure whether it's the source of this issue or not. (The new `cmd` still cannot display Unicode characters)

**Comment by giorgiotani** [comment]
Since release 5.8 PeaZip try to translate to widestring any UTF8 input file name containing characters outside user's machine codepage, as needed by Windows system API to correctly handle extended characters.
Unfortunately I have not a Windows machine with Chinese locale in order to directly test where the mechanism (that works for other locale I tested) falls short, and in what cases, but I've tried various possible solution to improve the mechanism in 5.8.1 and in new 5.9.0.
Please let me know if 5.9.0 works, or if older version were more fit to certaing characters set on a Chinese locale machine so I can do appropriate regression testing.

**Comment by lmy441900** [comment]
> Please let me know if 5.9.0 works

Oh yes it works. Recently I finally came back home and got PeaZip 5.9.1 installed on my own computer, and it can open all the archives on my computer.

Thank you for your attention.
