### ISSUE TITLE
Windows SmartScreen preventing peazip-5.9.0.WIN64.exe from running

### ISSUE THREAD

**Issue by stryk187** [giorgiotani/PeaZip#12]
[Win 8.1 x64]
Just tried to upgrade PeaZip (64-bit) to the latest version and I get an error:

> Windows SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

Upon clicking "More info" it shows:

> Publisher: Unknown Publisher
> App: peazip-5.9.0.WIN64.exe

Currently have 5.7.1 on my machine, and have been using it happily for quite some time. I don't recall any trouble installing it initially.

**Comment by giorgiotani** [comment]
Thank you for reporting. Probably the false positive issue was caused because the file is new and MS SmartScreen had not already updated to detect it as a safe application.
On VirusTotal I can see now all supported scan engine (including Microsoft's one) are reporting the package as safe https://www.virustotal.com/en/file/097571b9e86b73c0ad985171655aaf50e0f6bd47a8716e2b680363ec7bb236b8/analysis/
Please keep me informed if you experience the issue again.

**Comment by krashanoff** [comment]
This is most likely a contained issue.  I have run this program on Windows 7, 8.1, and 10 (Although I'm pretty sure that Windows 7 does not have SmartScreen) and from my experience none of them have mistakenly blocked the program from running.  However, I will attempt to replicate the issue under various conditions to determine what cause SmartScreen to block it.

**Comment by stryk187** [comment]
~21h later: Upgraded to the new version successfully this time. No warnings from SmartScreen nor anything else. Must have been too new for Microsoft's filters to recognize it yesterday, as Mr. Tani suggested. All is well, issue resolved. Lovely software by the way, incredibly versatile! Cheers for making it Free & Open Source!
